#!/usr/bin/env bash
# This script does FizzBuzz

for i in {1..100}
	case $i in
		$(($i%3)) == 0)
			echo "Fizz"
		$(($i%5)) == 0)
			echo "Buzz"
		$(($i%3)) -a $(($i%5)) == 0)
			echo "FizzBuzz"
		*)
			echo "$i"
	esac
done
		
