#!/usr/bin/env bash
# This script is going to tell a story with IFS and /etc/passwd

while [ IFS= read -r i ]; do
	f1=$( echo "$i" | cut -d: -f1 )
	f2=$( echo "$i" | cut -d: -f2 )
	f3=$( echo "$i" | cut -d: -f3 )
	f4=$( echo "$i" | cut -d: -f4 )
	f5=$( echo "$i" | cut -d: -f5 )
	f6=$( echo "$i" | cut -d: -f6 )
	f7=$( echo "$i" | cut -d: -f7 )

	echo "The user $f1 is part of the $f4 gang, lives in $f6 and rides $f7. $f3's place is protected by the passcode $f2, more info about the user here: $f5"
done < /etc/passwd
