#!/usr/bin/env bash
# This script is going to display Best School except for the 4th loop and 8th loop
i=1

while [ $i -le 10 ];
do
        if [ $i == 4 ]; then
                echo "bad luck"
                i=$(( i + 1 ))
        elif [ $i == 8 ]; then
                echo "good luck"
                i=$(( i + 1 ))
        else
                echo "Best School"
                i=$(( i + 1 ))
        fi
done
