#!/usr/bin/env bash
# This script is a clock
h=0
m=0

while [ $h -le 12];
do
	if [ $m -lt 1 ]; then
		echo "Hour: $h"
	elif [ $m -le 59 ]; then
		echo "$m"
	else
		h=$(( h + 1 ))
	fi
m=$(( m + 1 ));
done
