#!/usr/bin/env bash
# This script will display a list of the content in the current directory but only the part of the name after the - will be displayed

list="$(ls -x *-*)"

for i in "$list"; do
	text="${list#-}"
	echo "$text"
done
