#!/usr/bin/env bash
# This script will display a list of the content in the current directory but only the part of the name after the - will be displayed

list=$(ls)

for _ in $list; do
	text="${list#-}"
	echo "$text"
done
