#!/usr/bin/env bash
# this script will the file through a list of checks(does the file exist/not exist, is the file empty/not empty, is the file a regular file/not a regular file) and displays text when necessary
file="school"

if [ -e $file ]; then
	echo "school file exists"
	if [ -s $file ]; then
		echo "school file is not empty"
	elif [ ! -s $file ]; then
		echo "school file is empty"
	elif [ -f $file ]; then
		echo "school is a regular file"
	fi
else
	echo "school file does not exist"
fi
